os: linux
language: cpp
matrix:
  include:
    - env: TEST=shellcheck
      services:
        - docker
      script: |
        set -e
        shopt -s globstar nullglob
        CHECK=( **/*.sh )
        [[ ${#CHECK[@]} -eq 0 ]] && exit
        docker run -v $(pwd):$(pwd) -w $(pwd) \
          koalaman/shellcheck-alpine:v0.4.6 -x "${CHECK[@]}"
    - env: TEST=markdown
      services:
        - docker
      script: |
        set -e
        shopt -s globstar nullglob
        CHECK=( **/*.md )
        [[ ${#CHECK[@]} -eq 0 ]] && exit
        docker run -ti -v $(pwd):$(pwd) -w $(pwd) \
          mivok/markdownlint:0.4.0 "${CHECK[@]}"
    - env: TEST=make
      script: |
        set -e
        make --dry-run --warn-undefined-variables
    - env: TEST=docker
      services:
        - docker
      script: |
        set -e
        shopt -s globstar nullglob
        CHECK=( **/Dockerfile )
        [[ ${#CHECK[@]} -eq 0 ]] && exit
        for df in "${CHECK[@]}"; do
          docker run -ti -v$(pwd):$(pwd) -w $(pwd) \
            lukasmartinelli/hadolint hadolint --ignore DL3013 Dockerfile
        done
branches:
  only:
  - master
notifications:
  email: false
